[build]
  command = "bun run build"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  BUN_VERSION = "1.1.20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/docs"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/ping/*"
  to = "/.netlify/functions/server"
  status = 200
