export const SYSTEM_LIMITS = {
  MAX_MONITORS_PER_USER: 1,
  MAX_HEARTBEATS_PER_USER: 1,
} as const;

export const DEFAULT_CONFIG = {
  PROBE_INTERVAL_SECONDS: 60,
  PROBE_TIMEOUT_MS: 10000,
  DEFAULT_HTTP_EXPECTED_STATUS: 200,
  DEFAULT_HEARTBEAT_GRACE_PERIOD_SECONDS: 60,
  HEARTBEAT_CACHE_TTL_SECONDS: 3600,
  FLAPPING_WINDOW_SECONDS: 600,
  FLAPPING_MAX_CHANGES: 3,
} as const;
